#!/usr/bin/env node

/**
 * generate-docx.mjs — Markdown CV to ATS-friendly .docx via the `docx` package.
 *
 * Usage:
 *   node generate-docx.mjs <input.md> <output.docx>
 *
 * Reads a CV in Markdown form (default: cv.md), parses its sections, and
 * emits a clean ATS-friendly Word document using standard fonts (Calibri),
 * bold section headers, and bullet lists. No tables, colors, or images.
 *
 * Shares cv-parser.mjs with generate-pdf.mjs so both outputs derive from
 * the same parse — wording cannot drift between the two formats.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  BorderStyle,
  convertInchesToTwip,
} from 'docx';
import { readFile, writeFile } from 'fs/promises';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { mkdirSync } from 'fs';
import { parseMarkdown, inlineSegments } from './cv-parser.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
mkdirSync(resolve(__dirname, 'output'), { recursive: true });

function runsFromInline(text) {
  return inlineSegments(text).map(seg => new TextRun({ text: seg.text, bold: seg.bold }));
}

function buildDocument(doc) {
  const children = [];

  // Name
  children.push(new Paragraph({
    children: [new TextRun({ text: doc.name, bold: true, size: 36 })],
    spacing: { after: 60 },
  }));

  // Contact (one paragraph per line in cv.md, kept compact)
  for (const c of doc.contact) {
    children.push(new Paragraph({
      children: [new TextRun({ text: c, size: 20, color: '555555' })],
      spacing: { after: 40 },
    }));
  }

  // Spacer before sections
  children.push(new Paragraph({ text: '', spacing: { after: 120 } }));

  for (const section of doc.sections) {
    children.push(new Paragraph({
      children: [new TextRun({ text: section.title.toUpperCase(), bold: true, size: 24 })],
      spacing: { before: 240, after: 80 },
      border: {
        bottom: { color: '999999', space: 1, style: BorderStyle.SINGLE, size: 6 },
      },
    }));

    for (const block of section.blocks) {
      if (block.type === 'sub') {
        const s = block.data;
        children.push(new Paragraph({
          children: [new TextRun({ text: s.heading, bold: true, size: 22 })],
          spacing: { before: 160, after: 40 },
        }));
        if (s.meta) {
          children.push(new Paragraph({
            children: [new TextRun({ text: s.meta, italics: true, size: 20, color: '666666' })],
            spacing: { after: 60 },
          }));
        }
        if (s.intro) {
          children.push(new Paragraph({
            children: runsFromInline(s.intro),
            spacing: { after: 80 },
          }));
        }
        for (const b of s.bullets) {
          children.push(new Paragraph({
            children: runsFromInline(b),
            bullet: { level: 0 },
            spacing: { after: 40 },
          }));
        }
      } else if (block.type === 'bullet') {
        children.push(new Paragraph({
          children: runsFromInline(block.text),
          bullet: { level: 0 },
          spacing: { after: 40 },
        }));
      } else if (block.type === 'paragraph') {
        children.push(new Paragraph({
          children: runsFromInline(block.text),
          spacing: { after: 100 },
        }));
      }
    }
  }

  return new Document({
    creator: doc.name || 'career-ops',
    title: doc.name ? `${doc.name} - CV` : 'CV',
    description: 'CV generated by career-ops',
    styles: {
      default: {
        document: { run: { font: 'Calibri', size: 22 } },
      },
    },
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(0.6),
            right: convertInchesToTwip(0.7),
            bottom: convertInchesToTwip(0.6),
            left: convertInchesToTwip(0.7),
          },
        },
      },
      children,
    }],
  });
}

async function main() {
  const args = process.argv.slice(2);
  const inputPath = args[0];
  const outputPath = args[1];

  if (!inputPath || !outputPath) {
    console.error('Usage: node generate-docx.mjs <input.md> <output.docx>');
    process.exit(1);
  }

  const absIn = resolve(inputPath);
  const absOut = resolve(outputPath);

  console.log(`Input:  ${absIn}`);
  console.log(`Output: ${absOut}`);

  const md = await readFile(absIn, 'utf-8');
  const model = parseMarkdown(md);
  if (!model.name) {
    console.error('No # Name heading found in the markdown. Aborting.');
    process.exit(1);
  }

  const document = buildDocument(model);
  const buffer = await Packer.toBuffer(document);
  await writeFile(absOut, buffer);

  console.log(`Sections: ${model.sections.length}`);
  console.log(`Done: ${absOut} (${(buffer.length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => {
  console.error('DOCX generation failed:', err.message);
  process.exit(1);
});
